/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PanchsheelAarogyaDhaamRouteImport } from './routes/panchsheel-aarogya-dhaam'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchsheelAarogyaDhaamRoute = PanchsheelAarogyaDhaamRouteImport.update({
  id: '/panchsheel-aarogya-dhaam',
  path: '/panchsheel-aarogya-dhaam',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/panchsheel-aarogya-dhaam': typeof PanchsheelAarogyaDhaamRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellness': typeof WellnessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/panchsheel-aarogya-dhaam': typeof PanchsheelAarogyaDhaamRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellness': typeof WellnessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/journal': typeof JournalIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/panchsheel-aarogya-dhaam': typeof PanchsheelAarogyaDhaamRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellness': typeof WellnessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/panchsheel-aarogya-dhaam'
    | '/sitemap.xml'
    | '/wellness'
    | '/journal/$slug'
    | '/products/$slug'
    | '/journal/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/panchsheel-aarogya-dhaam'
    | '/sitemap.xml'
    | '/wellness'
    | '/journal/$slug'
    | '/products/$slug'
    | '/journal'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/panchsheel-aarogya-dhaam'
    | '/sitemap.xml'
    | '/wellness'
    | '/journal/$slug'
    | '/products/$slug'
    | '/journal/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PanchsheelAarogyaDhaamRoute: typeof PanchsheelAarogyaDhaamRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WellnessRoute: typeof WellnessRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchsheel-aarogya-dhaam': {
      id: '/panchsheel-aarogya-dhaam'
      path: '/panchsheel-aarogya-dhaam'
      fullPath: '/panchsheel-aarogya-dhaam'
      preLoaderRoute: typeof PanchsheelAarogyaDhaamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PanchsheelAarogyaDhaamRoute: PanchsheelAarogyaDhaamRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WellnessRoute: WellnessRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
